// Builds report.md from the public template and bundled data only.
// Usage: node scripts/m7_build_report.mjs [root=.]
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  auditBlock, costCyclesBlock, costLinesBlock, costTotalsBlock, confirmedCaseBlock, cycleAccountingBlock, cycleLinesBlock, gpuBlock, hacksBlock, labelAuditBlock, exploratoryDetectorBlock, nonCheaterPositivesBlock, pooledAccountingBlock, pooledBlock,
  provenanceBlock, stallBlock, summaryBlock, trustLevelsBlock, trustEventsBlock,
} from './m7_blocks.mjs';
import { cycleWindows, parseGpuLog } from './m7_gpu.mjs';
import { parseCsv } from './m7_metrics.mjs';
import { evaluateP0, p0Inputs, renderP0 } from './m7_results.mjs';
import { parseDriverStalls, stallTable } from './m7_stall.mjs';

/** Replace every {{name}} with its block. An unknown marker or an unused block is an error. */
export function fillTemplate(template, blocks) {
  const used = new Set();
  const out = template.replace(/\{\{([\w-]+)\}\}/g, (marker, name) => {
    if (!(name in blocks)) throw new Error(`no block for ${marker}`);
    used.add(name);
    return String(blocks[name]).trimEnd();
  });
  for (const name of Object.keys(blocks)) if (!used.has(name)) throw new Error(`unused block: ${name}`);
  return out;
}

/** Every file under dir, sorted, with size and sha256. Paths are relative to dir. */
export function listFiles(dir) {
  const out = [];
  const walk = (d) => {
    for (const name of readdirSync(d).sort()) {
      const full = join(d, name);
      if (statSync(full).isDirectory()) walk(full);
      else out.push({ path: relative(dir, full).split('\\').join('/'), bytes: statSync(full).size, sha256: createHash('sha256').update(readFileSync(full)).digest('hex') });
    }
  };
  walk(dir);
  return out.sort((a, b) => a.path.localeCompare(b.path));
}

export function buildReport(root = '.') {
  const supplemental = new Set(['attempt-cost.csv','task-stages.csv','gpu-pilot.csv','journal-size.csv','genkan-main.log','hack-audit.json','trust-events.json']);
  const main = (name) => supplemental.has(name) ? join(root,'data/support',name==='genkan-main.log'?'driver-stalls.log':name) : join(root,'data/exports/main',name==='cycle-metrics.jsonl'?'metrics.jsonl':name);
  const read = (path) => readFileSync(path, 'utf8');
  const rows = parseCsv(read(main('cycles.csv')));
  const costs = parseCsv(read(main('attempt-cost.csv'))).filter((r) => r.split === 'main');
  const stages = parseCsv(read(main('task-stages.csv'))).filter((r) => r.split === 'main');
  const { samples } = parseGpuLog(read(main('gpu-pilot.csv')), 0);
  const stalls = stallTable(parseCsv(read(main('journal-size.csv'))), parseDriverStalls(read(main('genkan-main.log')), 'main'));
  const p0 = evaluateP0(p0Inputs(rows));
  crossCheckMetrics(rows, read(main('cycle-metrics.jsonl')));
  const prov = JSON.parse(read(join(root, 'data/support/provenance.json')));
  const cycleMetrics = read(main('cycle-metrics.jsonl')).trim().split('\n').map((line)=>JSON.parse(line));
  const audit = JSON.parse(read(main('hack-audit.json')));
  const cases = JSON.parse(read(join(root, 'data/labels/confirmed-cases.json')));
  const trustEvents = JSON.parse(read(main('trust-events.json')));
  const labelAudit = JSON.parse(read(join(root, 'data/labels/sample-analysis.json')));
  const blocks = {
    'generated-note': `Generated by \`scripts/m7_build_report.mjs\` from \`data/\`. Do not edit the tables by hand: change the data or code and build again. Text outside the tables is in \`scripts/report.template.md\`.`,
    summary: summaryBlock(p0, rows, audit, cases),
    provenance: provenanceBlock(prov, listFiles(join(root, 'data/exports'))),
    p0: renderP0(p0),
    pooled: pooledBlock(rows),
    'pooled-accounting': pooledAccountingBlock(cycleMetrics),
    'cycle-accounting': cycleAccountingBlock(cycleMetrics),
    audit: auditBlock(audit),
    'confirmed-cases': confirmedCaseBlock(rows,cases),
    'label-audit': labelAuditBlock(labelAudit),
    'exploratory-detector': exploratoryDetectorBlock(labelAudit,audit),
    'cycle-lines': cycleLinesBlock(rows),
    'trust-levels': trustLevelsBlock(rows),
    'trust-events': trustEventsBlock(trustEvents),
    hacks: hacksBlock(rows),
    'noncheater-positives': nonCheaterPositivesBlock(rows),
    'cost-cycles': costCyclesBlock(stages, costs),
    'cost-lines': costLinesBlock(costs),
    'cost-totals': costTotalsBlock(stages, costs),
    gpu: gpuBlock(samples, cycleWindows(stages)),
    stall: stallBlock(stalls),
  };
  return `${fillTemplate(read(join(root, 'scripts/report.template.md')), blocks)}\n`;
}

/** The cycle metrics file (bench cycle metrics) must agree with the recomputation from the export. */
function crossCheckMetrics(rows, jsonl) {
  const byCycle = new Map(jsonl.trim().split('\n').map((l) => JSON.parse(l)).map((c) => [c.cycle, c]));
  for (const c of byCycle.values()) {
    if (c.failed !== 0 || c.rerunRequired || c.protocol.flagged) throw new Error(`cycle ${c.cycle} is not clean in cycle-metrics.jsonl`);
  }
  const items = [...byCycle.values()].reduce((a, c) => a + c.items, 0);
  if (items !== rows.length) throw new Error(`cycle-metrics.jsonl counts ${items} items, cycles.csv has ${rows.length}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const root = process.argv[2] ?? '.';
  writeFileSync(join(root, 'report.md'), buildReport(root));
  console.log(`wrote ${join(root, 'report.md')}`);
}
